require("dotenv").config()

module.exports = {
	TEMPLATEFILEPATH: process.env.TEMPLATEFILEPATH,
	UPDATETEMPLATEFILEPATH: process.env.UPDATETEMPLATEFILEPATH,
	OUTPUTWALPAPERPATH: process.env.OUTPUTWALPAPERPATH,
	INPUTBROWSERHTMLPATH: process.env.INPUTBROWSERHTMLPATH
}
